---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-web
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
    sidecar.istio.io/inject: "true"
spec:
  releaseName: nordmart-dev-web
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "web"
    deployment:
      podLabels:
        app: web
      image:
        repository: stakater/stakater-nordmart-web
        tag: v0.0.1
      imagePullSecrets: "docker-registry-nexus-secret"
      fluentdConfigAnnotations:
        regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+)
          (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
        regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
        timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 4200
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 4200
      volumes: {}
      env:
      - name: PORT
        value: "4200"
      - name: SECURE_GW_ENDPOINT
        value: "https://gateway-dev.DOMAIN/"
      - name: SSO_URL
        value: "https://keycloak-dev.DOMAIN"
    service:
      ports:
      - port: 4200
        name: tcp
        protocol: TCP
        targetPort: 4200
    rbac:
      create: true
      serviceAccount:
        create: true
    configMap:
      enabled: false
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-dev-virtualservice
  namespace: istio-system
spec:
  hosts:
    - "web-dev.DOMAIN"
  gateways:
    - istio-gateway
  http:
    - route:
        - destination:
            host: web.nordmart-dev-apps.svc.cluster.local