apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-nexus-secret
  namespace: nordmart-dev-apps
stringData:
  .dockercfg: '{ "docker.release.stakater.com:443": { "auth" :"c3RhY2thdG9yLWFkbWluOkBxd2VydHk3ODY=" }, "https://index.docker.io/v1/": { "auth": "c3Rha2F0ZXJ1c2VyOkBxd2VydHk3ODY=" }}'
type: kubernetes.io/dockercfg