---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nordmart-dev-cart
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-dev-cart
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.5
  values:
    applicationName: "cart"
    deployment:
      podLabels:
        app: cart
      image:
        repository: docker.release.stakater.com:443/stakater/cart
        tag: v0.0.3
      volumes: {}
      env:
      - name: CATALOG_ENDPOINT
        value: "catalog.nordmart-dev-apps:8080"
      imagePullSecrets: "docker-registry-nexus-secret"
    service:
      annotations:
        config.xposer.stakater.com/Domain: workshop.stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-dev'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-dev.{{.Domain}}'
        config.xposer.stakater.com/TLS: 'true'
        config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: external-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: locally
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false
