apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cart-nordmat-dev
  namespace: nordmart-dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.0.*
spec:
  releaseName: cart-nordmat-dev
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.2
  values:
    applicationName: "cart"
    deployment:
      image:
        repository: docker.release.stakater.com:443/stakater/cart
        tag: v0.0.1
      env:
      - name: CATALOG_ENDPOINT
        value: "catalog.nordmart-dev:8080"
      imagePullSecrets: "docker-registry-nexus-secret"
    service:
      annotations:
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}'
        config.xposer.stakater.com/IngressURLPath: /
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Domain}}'
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap: {}