---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nordmart-dev-cart
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-dev-cart
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.5
  values:
    applicationName: "cart"
    deployment:
      podLabels:
        app: cart
      image:
        repository: docker.release.stakater.com:443/stakater/cart
        tag: SNAPSHOT-PR-2-1
      volumes:
      env:
      - name: CATALOG_ENDPOINT
        value: "catalog.nordmart-dev-apps:8080"
      imagePullSecrets: "docker-registry-nexus-secret"
    service:
      annotations: 
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
