apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: prometheus-rulefiles
    release: stakater-monitoring-prometheus-operator
    kind: apps
    app: stakater
  name: prometheus-rules-catalog-dev
  namespace: monitoring
spec:
  groups:
  - name: application.rules
    rules:
    - alert: HighCatalogDevApiUsage
      annotations:
        message: 'Api usage is greater than 10.'
      expr: count_requests_total > 10
      for: 10s
      labels:
        kind: apps
        severity: warning
