# A sample service monitor to scrape data from this app
apiVersion: v1
kind: List
items:
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: stakater-nordmart-catalog-dev-monitor
    labels:
      release: stakater-monitoring-prometheus-operator
    namespace: monitoring
  spec:
    jobLabel: ""
    selector:
      matchLabels:
        release: nordmart-prod-catalog     # All services with this label will be monitored.
    namespaceSelector:
      matchNames:
      - nordmart-dev-apps       # The namespace in which the application will be deployed
    endpoints:
      - interval: 10s
        path: /actuator/prometheus     # The endpoint of service from which prometheus will scrape data
        port: http