---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nordmart-dev-catalog
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-dev-catalog
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.2
  values:
    applicationName: "catalog"
    deployment:
      podLabels:
        app: catalog
      image:
        repository: docker.release.stakater.com:443/stakater/catalog
        tag: v0.0.8
      imagePullSecrets: "docker-registry-nexus-secret"
    service:
      annotations:annotations: {}
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap: {}
