apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nordmart-dev-gateway
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-dev-gateway
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.2
  values:
    applicationName: "gateway"
    deployment:
      podLabels:
        app: gateway
      image:
        repository: docker.release.stakater.com:443/stakater/gateway
        tag: v0.0.2
      imagePullSecrets: "docker-registry-nexus-secret"
      env:
      - name: CATALOG_API_HOST
        value: "catalog.nordmart-dev"
      - name: CATALOG_API_PORT
        value: "8080"
      - name: INVENTROY_API_HOST
        value: "inventory.nordmart-dev"
      - name: INVENTROY_API_PORT
        value: "8080"
      - name: DISABLE_CART_DISCOVERY
        value: "false"
      - name: CART_API_HOST
        value: "cart.nordmart-dev"
      - name: CART_API_PORT
        value: "8080"
      - name: HTTP_PORT
        value: "8080"
    service:
      annotations: {}
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap: {}