---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nordmart-dev-gateway
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-dev-gateway
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.5
  values:
    applicationName: "gateway"
    deployment:
      podLabels:
        app: gateway
      image:
        repository: docker.release.stakater.com:443/stakater/gateway
        tag: v0.0.3
      imagePullSecrets: "docker-registry-nexus-secret"
      volumes: {}
      env:
      - name: CATALOG_API_HOST
        value: "catalog.nordmart-dev-apps"
      - name: CATALOG_API_PORT
        value: "8080"
      - name: INVENTROY_API_HOST
        value: "inventory.nordmart-dev-apps"
      - name: INVENTROY_API_PORT
        value: "8080"
      - name: DISABLE_CART_DISCOVERY
        value: "false"
      - name: CART_API_HOST
        value: "cart.nordmart-dev-apps"
      - name: CART_API_PORT
        value: "8080"
      - name: HTTP_PORT
        value: "8080"
    service:
      annotations:
        config.xposer.stakater.com/Domain: workshop.stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-dev'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-dev.{{.Domain}}'
        config.xposer.stakater.com/TLS: 'true'
        config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: external-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: locally
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false