apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nordmart-dev-inventory
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-dev-inventory
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.2
  values:
    applicationName: "inventory"
    deployment:
      podLabels:
        app: inventory
      image:
        repository: docker.release.stakater.com:443/stakater/inventory
        tag: v0.0.1
      imagePullSecrets: "docker-registry-nexus-secret"
    service:
      annotations:
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}'
        config.xposer.stakater.com/IngressURLPath: /
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Domain}}'
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap: {}