apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: nordmart-dev-apps
spec:
  encryptedData:
    mysql_password: AgAnFCPBzu+vAQgaxt6DF7Aw+E/smjyJ93kf8749wQ+ifNRGrXuZbqILsaPLP+Z2aRmhGcneXPKqnSzImHxGE5dlb9nS+tKWUEuo8aXE5FQH4cWuEowXGGUYFv6TQcsZKZIpo+B9S+sO4T1wKdD/sPOVVYtrvg7mSrJ+4eWM1yTDS6c3f6bHGm06zoP+7f33FfurLQ/Jy2Pb8GrGH5PhzwIm36JdJDzFBecYISSFN0M4LAgM4IbyreYgzM20WX+vA9Ea57fwDNpWZ9/RMwUIC1pucwjHdvW/pBKw9496xTAcfU0ZjFwVQNvvulp8uNKA2AqWFYjRIr+22lZVTseuPp4B8kxdJIn13IIrZzQUq4Taye4tHHwP+Hi3deOZQ9JTnDn8/1pCG+OH3e1Xw7PwtKDKdRsm5lJI18CEv7jrlx1BR5nVCNP1vZV9HxZ/2P0nHfIhLiIG7+1Xk36ORwfcyMmZHFYX2qV62QMlOWxRBWM4YfkLt0l2eI1hkt0qME7mUitzJmsD1V9eK7JzuGM1NpRmYcphoyHhgqGCWLLDZaYT0augfFTWF7hHhse++p09s/6pFuOsoSbus6FwbP8r9gcUWcljEMXs0Rb2QMyR9EgAjjdEjGzWKzonLKdRervUJEp7wP+caS4TlaGWhJOiwx8z6XOLQKJfLMLP13qwpR+dydJmSoqjqYzZQlH+X5Lcr4EvxOS4Fm4V+kQ=
    mysql_username: AgCitexDp0+IEkjC/tCC3LGhM5Pu1/qMusJw6KanUcljz8eG7nzIB1b0Xsc8aehpINpwZwqFXNu9doconCbdfrRjpYhuuKm13ONB6Urh69OubJU3GeVNF8lHR2Kzqk2Eos5uREr6+PB22aaY3NoMe/fMVo5MTU+7Y9umZNqOSbn+M4wlTXaXHX87KNO/Gfs64UAry1BvzXXT7vsWVAedVn55fNXdJwHAdhQ23STpX6efoNuHLvuwWcW2DoK+/l1+bhDvh2T5oKGhB+k1Nk8zigBPxbcdzpQZB/zGaYsaVM8WExVP98Ut3PNDjJqCh1F3VkSZhaEsOzOrNIy5UOEd7zHvvUDhEIfzoWSqmKzMqMTYzu73wCIz6+00yk9O33E3lMrhXURplOo08XeSEzUiP/ydtku5QoRYUESrjyoMOPveNpZFJfP2kGcs3cusj3CT1X5/iHormtpKhndi8UEpWZLp7pZRqTbn3lDNl1WZCeLmGWr/4NkwWa7sE34Y6wA68hjWmxN1N2nha+1Dfk2uucDZg/9ljRrvNsiOd8gE56GqFPhlsYPPeWETzaMIckLafEulnRrLZPdT7y0pUq5/fbvljQWKUw05NqTg7gcqbNFGsBc3yfe5kwa7aeIUIA7RW0xj6mptxkakd/qjQGA9zlNCKKY303xFA1q05gaBnqSuywt81U20fgxBKoXM+dnK+XTGLZFG
  template:
    metadata:
      name: mysql-secret
      namespace: nordmart-dev-apps
    type: Opaque
