---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nordmart-dev-web
  namespace: nordmart-dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.0.*
spec:
  releaseName: nordmart-dev-web
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.2
  values:
    applicationName: "web"
    deployment:
      podLabels:
        app: web
      image:
        repository: docker.release.stakater.com:443/stakater/web
        tag: 0.0.0-PR-8-1-SNAPSHOT
      imagePullSecrets: "docker-registry-nexus-secret"
      env:
      - name: PORT
        value: "4200"
      # - name: SSO_URL
      #   value: "https://keycloak.global.stakater.com"
      - name: SECURE_COOLSTORE_GW_ENDPOINT
        value: "https://gateway.stakater.com"
    service:
      ports:
      - port: 4200
        name: web
        protocol: TCP
        targetPort: 4200
      annotations:
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}'
        config.xposer.stakater.com/IngressURLPath: /
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Domain}}'
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap: {}
