---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nordmart-dev-web
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-dev-web
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.5
  values:
    applicationName: "web"
    deployment:
      podLabels:
        app: web
      image:
        repository: docker.release.stakater.com:443/stakater/web
        tag: v0.0.8
      imagePullSecrets: "docker-registry-nexus-secret"
      volumes: {}
      env:
      - name: PORT
        value: "4200"
      # - name: SSO_URL
      #   value: "https://keycloak.global.stakater.com"
      - name: SECURE_COOLSTORE_GW_ENDPOINT
        value: "https://gateway.stakater.com"
    service:
      ports:
      - port: 4200
        name: web
        protocol: TCP
        targetPort: 4200
      annotations: []
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false
