---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-web
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
spec:
  releaseName: nordmart-dev-web
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.11
  values:
    applicationName: "web"
    deployment:
      annotations:
        sidecar.istio.io/inject: "true"
      additionalPodAnnotations:
        sidecar.istio.io/inject: "true"
      podLabels:
        app: web
      image:
        repository: docker-delivery.workshop.stakater.com:443/stakater-lab/web
        tag: 0.0.0-PR-22-1-SNAPSHOT
      imagePullSecrets: "docker-registry-nexus-secret"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 4200
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 4200
      volumes: {}
      env:
      - name: PORT
        value: "4200"
      # - name: SSO_URL
      #   value: "https://keycloak.global.stakater.com"
      - name: SECURE_GW_ENDPOINT
        value: "https://gateway-dev.workshop.stakater.com/"
    service:
      ports:
      - port: 4200
        name: web
        protocol: TCP
        targetPort: 4200
      additionalLabels:
        expose: "true"
      annotations:
        config.xposer.stakater.com/Domain: stackator.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-dev'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-dev.{{.Domain}}'
        config.xposer.stakater.com/TLS: 'true'
        config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: external-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: locally
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false
