apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: web-nordmat-dev
  namespace: nordmart-dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.0.*
spec:
  releaseName: web-nordmat-dev
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.2
  values:
    applicationName: "web"
    deployment:
      image:
        repository: docker.release.stakater.com:443/stakater/web
        tag: v0.0.7
      imagePullSecrets: "docker-registry-nexus-secret"
      env:
      - name: PORT
        value: "4200"
      # - name: SSO_URL
      #   value: "https://keycloak.global.stakater.com"
      - name: SECURE_COOLSTORE_GW_ENDPOINT
        value: "https://gateway.stakater.com"
    service:
      annotations:
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}'
        config.xposer.stakater.com/IngressURLPath: /
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Domain}}'
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap: {}